rootProject.name = 'j-debug-lab-exercises'

include 'common'
include 'exercise01-nullpointer'
include 'exercise02-nullpointer-di'
include 'exercise03-index-loop'
include 'exercise04-index-emptylist'
include 'exercise05-divide-zero'
include 'exercise06-number-format'
include 'exercise07-classpath'
include 'exercise08-illegal-argument'
include 'exercise09-file-path'
include 'exercise10-io-permission'
include 'exercise11-concurrent-mod'
include 'exercise12-illegal-state'
include 'exercise13-sql-syntax'
include 'exercise14-sql-connection'
include 'exercise15-json-parse'
include 'exercise16-http-unknown-host'
include 'exercise17-thread-interrupt'
include 'exercise18-memory-leak'
include 'exercise19-stackoverflow'
include 'exercise20-custom-exception'